# Generated by Django 3.1.3 on 2021-01-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelUser',
        ),
    ]
