# Generated by Django 3.1.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelPaket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=100)),
                ('destinasi', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('harga', models.IntegerField()),
                ('lama_hari', models.IntegerField()),
                ('tgl_berangkat', models.DateField()),
                ('tgl_dibuat', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='imagesPaket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paket.modelpaket')),
            ],
        ),
    ]
