# Generated by Django 3.1.1 on 2020-11-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespaket',
            name='id_paket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Paket.modelpaket'),
        ),
        migrations.AlterField(
            model_name='modelpaket',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
