# Generated by Django 3.1.1 on 2020-12-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltransaksi',
            name='status',
            field=models.CharField(default=0, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltransaksi',
            name='totalHarga',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltransaksi',
            name='token',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
