# Generated by Django 3.1.1 on 2020-12-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaksi', '0002_auto_20201207_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltransaksi',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modeltransaksi',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
